import type { Asset } from '@/utilities/types'

export const assets: Asset = {
  _ui_color_palette: [
    '/videos/_work/_ui_color_palette/article-asset-1.mp4',
    '/videos/_work/_ui_color_palette/article-asset-2.mp4',
    '/videos/_work/_ui_color_palette/article-asset-3.mp4',
    '/videos/_work/_ui_color_palette/article-asset-1.webm',
    '/videos/_work/_ui_color_palette/article-asset-2.webm',
    '/videos/_work/_ui_color_palette/article-asset-3.webm',
  ],
  _jeprendsquoi: [
    '/images/_work/_jeprendsquoi/illustration.webp',
    '/images/_work/_jeprendsquoi/background.svg',
    '/images/_work/_jeprendsquoi/article-asset-1.webp',
    '/images/_work/_jeprendsquoi/article-asset-2.webp',
    '/images/_work/_jeprendsquoi/article-asset-3.webp',
    '/images/_work/_jeprendsquoi/article-asset-4.webp',
    '/images/_work/_jeprendsquoi/article-asset-5.webp',
    '/images/_work/_jeprendsquoi/article-asset-6.webp',
    '/images/_work/_jeprendsquoi/article-asset-7.gif',
    '/images/_work/_jeprendsquoi/article-asset-8.gif',
  ],
  _jean_bobby_radio: [
    '/images/_work/_jean_bobby_radio/article-asset-1.webp',
    '/images/_work/_jean_bobby_radio/article-asset-2.webp',
  ],
  _iobeya_mobile_ds: [
    '/images/_work/_iobeya_mobile_ds/article-asset-1.webp',
    '/images/_work/_iobeya_mobile_ds/article-asset-2.webp',
    '/images/_work/_iobeya_mobile_ds/article-asset-3.png',
    '/images/_work/_iobeya_mobile_ds/article-asset-4.webp',
    '/images/_work/_iobeya_mobile_ds/article-asset-5.webp',
    '/images/_work/_iobeya_mobile_ds/article-asset-6.webp',
    '/images/_work/_iobeya_mobile_ds/article-asset-7.webp',
    '/images/_work/_iobeya_mobile_ds/article-asset-8.webp',
    '/images/_work/_iobeya_mobile_ds/article-asset-9.webp',
  ],
  _awesome_ipsums: [
    '/images/_work/_awesome_ipsums/article-asset-1.webp',
    '/images/_work/_awesome_ipsums/article-asset-2.webp',
    '/images/_work/_awesome_ipsums/article-asset-3.webp',
    '/images/_work/_awesome_ipsums/article-asset-4.webp',
    '/images/_work/_awesome_ipsums/ending-asset-1.svg',
    '/images/_work/_awesome_ipsums/ending-asset-2.svg',
    '/images/_work/_awesome_ipsums/ending-asset-3.svg',
  ],
  _iobeya_whiteboard: [
    '/images/_work/_iobeya_whiteboard/background.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-1.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-2.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-3.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-4.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-5.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-6.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-7.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-8.webp',
    '/images/_work/_iobeya_whiteboard/article-asset-9.svg',
    '/images/_work/_iobeya_whiteboard/article-asset-10.svg',
    '/images/_work/_iobeya_whiteboard/article-asset-11.webp',
    '/videos/_work/_iobeya_whiteboard/article-asset-1.mp4',
  ],
  lab: [
    '/images/_lab/sd/asset-1.webp',
    '/images/_lab/sd/asset-2.webp',
    '/images/_lab/sd/asset-3.webp',
    '/images/_lab/sd/asset-4.webp',
    '/images/_lab/sd/asset-5.webp',
    '/images/_lab/sd/asset-6.webp',
    '/images/_lab/sd/asset-7.webp',
  ],
}
